a = 2
b = 4.5
print(a + b)
number_1 = int(input('Введите число от 1 до 10: '))
number_2 = float(input('Введите число от 1 до 10: '))
print(number_1 + 10)
print(number_2 + 10)
print(number_1//number_2)
name = input('Введите Ваше имя: ')
print('Привет, ' + name + '!' + ' Как дела?')
float('1')
int('2')
bool(1)
bool('')
bool('0')